# Welcome to Jekyll!
#

# Site settings
title: Gahn Mungarndee
description: |
  A visionary. A thinker. A student fueled by coffee.
owner: Gahn Mungarndee # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: gahn@mungarndee.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gahnmungarndee.me" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  linkedin-square: https://linkedin.com/in/gahn-mungarndee
  email: mailto:gahn@mungarndee.com?subject=[Hey!]
  #github: https://github.com/itsgahndi
  facebook-official: https://facebook.com/gahn.mungarndee
  instagram: https://instagram.com/venturingcrew2992
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #flickr:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
